version: '3.9'

services:
  springboot-app:
    image: wiremock-demo-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"   # Spring Boot API


